import type { UITheme } from './types.js';

export const UI_THEMES: Record<string, UITheme> = {
  medieval: {
    name: 'Medieval',
    bgColor: '#2a1f1a',
    borderColor: '#8b6914',
    accentColor: '#c49a2a',
    textColor: '#f0e6d2',
    hoverColor: '#d4a832',
    disabledColor: '#555555',
    borderWidth: 3,
    cornerRadius: 2,
  },
  dark: {
    name: 'Dark Fantasy',
    bgColor: '#1a1a2e',
    borderColor: '#4a4a6a',
    accentColor: '#7b2d8e',
    textColor: '#e0e0e0',
    hoverColor: '#9b3dae',
    disabledColor: '#3a3a4a',
    borderWidth: 2,
    cornerRadius: 1,
  },
  nature: {
    name: 'Nature',
    bgColor: '#1a2e1a',
    borderColor: '#3d6b3d',
    accentColor: '#5ba85b',
    textColor: '#d2f0d2',
    hoverColor: '#6bc86b',
    disabledColor: '#3a4a3a',
    borderWidth: 2,
    cornerRadius: 3,
  },
  ice: {
    name: 'Ice Kingdom',
    bgColor: '#1a2a3e',
    borderColor: '#4a7a9a',
    accentColor: '#6aaace',
    textColor: '#d2e6f0',
    hoverColor: '#8abade',
    disabledColor: '#3a4a5a',
    borderWidth: 2,
    cornerRadius: 2,
  },
  fire: {
    name: 'Fire & Brimstone',
    bgColor: '#2e1a1a',
    borderColor: '#8b3a14',
    accentColor: '#d44a1a',
    textColor: '#f0d2b2',
    hoverColor: '#e46a3a',
    disabledColor: '#4a3a3a',
    borderWidth: 3,
    cornerRadius: 1,
  },
  royal: {
    name: 'Royal',
    bgColor: '#1a1a3e',
    borderColor: '#6a4a8e',
    accentColor: '#a070d0',
    textColor: '#e6d2f0',
    hoverColor: '#b090e0',
    disabledColor: '#3a3a5a',
    borderWidth: 3,
    cornerRadius: 2,
  },
};
